### ISSUE TITLE
Copper handles yaml files beginning with `---` incorrectly

### ISSUE THREAD

**Issue by eyalzek** [cloud66-oss/copper#16]
YAML files can optionally being with 3 dashes, e.g `---`. Copper will parse that as a resource. For example, given the manifest:

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
spec:
  template:
    spec:
      containers:
      - image: busybox
        name: busybox
```

and rule:

```
rule DeploymentApiVersion ensure {
    fetch("$[?(@['kind'] == 'Deployment')].apiVersion").first == "apps/v1"
}
```

copper will fail for the opening dashes:

```
$ copper check --rules rule.cop --file deployment.yaml 
Validating part 0
	DeploymentApiVersion - FAIL
Validating part 1
	DeploymentApiVersion - PASS
```
